@startuml
class PerformanceTester {
    + serializeLog : bool = false
    + summary : string
    + GetTimeTables() : string
    + TestAllTilemapsOnce() : void
    + TestTilemapNTimes(stm:SerializableTilemap, outputSize:Vector3Int, patternSize:int, numberOfTests:int, enableRotations:bool, enableReflections:bool) : string
    + TestAllNTimes() : void
}
class "List`1"<T> {
}
MonoBehaviour <|-- PerformanceTester
PerformanceTester --> "model" WfcModel
PerformanceTester --> "tilemapsToTest<SerializableTilemap>" "List`1"
@enduml
